### PR TITLE
Support variable length, UTF-8 encoded scalar strings in attributes.

### LINKED ISSUE #79: Write string attributes as a string
When using `h5writeAttributes`, it seems that we end up with arrays of fixed-width strings (probably `H5T_C_S1`?). This confuses other HDF5 readers that expect an actual string (usually one of the `H5T_CSET` options).

It seems like it would be generally useful to include an `encoding=` option in `h5writeAttributes` that allows us to switch to ASCII or UTF-8 when a length-1 character vector is supplied. A similar option might also be useful for `h5writeDataset` as well. For all other character vectors, this argument can be ignored, with a warning, or we can error out and say that they can't do that.

### PR DESCRIPTION
**Pull request by LTLA**
Closes #79. To illustrate:

```r
# in R:
library(rhdf5)

file <- "whee.h5"
unlink(file)
handle <- H5Fcreate(file)

rhdf5::h5createGroup(handle, "WHEEE")
ghandle <- H5Gopen(handle, "WHEEE")

h5writeAttribute("AARON_WAS_HERE", ghandle, "last-visitor", cset="UTF8", variableLength=TRUE, scalar=TRUE)

H5Gclose(ghandle)
H5Fclose(handle)
```

Which gives us a `h5dump whee.h5` of:

```
HDF5 "whee.h5" {
GROUP "/" {
   GROUP "WHEEE" {
      ATTRIBUTE "last-visitor" {
         DATATYPE  H5T_STRING {
            STRSIZE H5T_VARIABLE;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_UTF8;
            CTYPE H5T_C_S1;
         }
         DATASPACE  SCALAR
         DATA {
         (0): "AARON_WAS_HERE"
         }
      }
   }
}
}
```

and with **h5py**:

```python
import h5py
X = h5py.File("whee.h5")
dict(X["WHEEE"].attrs)
## {'last-visitor': 'AARON_WAS_HERE'}
```

Tests and documentation for all the new functionality is left as an exercise for someone else.

### CODE REVIEW

**Comment by LTLA** [comment]
What say you @grimbough?

**Comment by grimbough** [comment]
Thanks @LTLA . I'll take a look at this over Easter.

**Comment by LTLA** [comment]
Ended up just adding the tests and docs myself. I don't mind it being merged as-is, but given that you're going to look at it anyway, you might as well extrapolate the extra features to string datasets rather than just attributes. To recap, these are:

- Support for creation of and writing to scalar spaces when `dim=NULL`.
- Support for UTF-8 encoding.
- Support for variable-length strings.

**Comment by LTLA** [comment]
Nuge.

**Comment by LTLA** [comment]
Hello? Ground control to @grimbough ?

**Comment by LTLA** [comment]
image

**Pull request merged**
